apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-creator
  namespace: default  # Change the namespace if you want it to be in a different one
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-creator-binding
  namespace: default  # Change the namespace if you want it to be in a different one
subjects:
- kind: User
  name: Sandra  # The user you want to bind to the Role
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sa-creator
  apiGroup: rbac.authorization.k8s.io
