apiVersion: v1
kind: Namespace
metadata:
  name: man-sinh-lee
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: man-sinh-lee
  namespace: man-sinh-lee
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: man-sinh-lee
  name: full-access
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps", "batch", "extensions"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-only-binding
subjects:
- kind: ServiceAccount
  name: man-sinh-lee
  namespace: man-sinh-lee
roleRef:
  kind: ClusterRole
  name: read-only
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-access-binding
  namespace: man-sinh-lee
subjects:
- kind: ServiceAccount
  name: man-sinh-lee
  namespace: man-sinh-lee
roleRef:
  kind: Role
  name: full-access
  apiGroup: rbac.authorization.k8s.io
