apiVersion: v1
kind: Namespace
metadata:
  name: man-sinh-lee-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: man-sinh-lee-namespace
  name: full-permissions
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-permissions-binding
  namespace: man-sinh-lee-namespace
subjects:
- kind: User
  name: man-sinh-lee
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: full-permissions
  apiGroup: rbac.authorization.k8s.io
